project_id = "brxbtgzaumryxflkykpp"

[functions.transcode-video]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.get-video-duration]
verify_jwt = true
